### ISSUE TITLE
Unicode token not supported

### ISSUE THREAD

**Issue by byzod** [dfaker/embedding-to-png-script#1]
Use `中文字` as token shows `□□□` in result image

**Comment by dfaker** [comment]
Are we using roboto as the default font or something else with Chinese character support?
And does the same issue occur in x/y plot?

**Comment by byzod** [comment]
I didn't catch you, what font are we talking about? I didn't change anything about font, it's [sd-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) default I think

What is `x/y plot` thing you mentioned? If you mean the filename of result image, it works perfectly with unicode characters. If you mean embedding-to-png feature in x/y plot, I don't know how to do that

**Comment by dfaker** [comment]
There's another script called "x/y plot" it uses the same mechanism for printing text out, just tested it and same boxes, I'll hunt down some Unicode fonts and check compatibility.

**Comment by byzod** [comment]
OK, it fails too, then this is a webui bug, I'll report there, you can close this

**Comment by dfaker** [comment]
The only bug on that side was in my code too, closed out now and it should all respect the font you set in settings.
