### ISSUE TITLE
Add different width/height for SD 2.0 support

### ISSUE THREAD

**Issue by artemisiaaaa** [dfaker/embedding-to-png-script#4]
when I use it for an embedding I made with SD 2.0 (768-v-ema-ckpt) the image gets distorted because it defaults to 512x512. would be cool if you added 768x768 or an option to choose the same resolution as set with the main web ui width & height sliders

**Comment by dfaker** [comment]
distorted? You mean the network works less well at smaller sizes?

In any case dimension override removed, it'll use whatever the generate run uses.
